### ISSUE TITLE
Bug: Player changes after invalid move

### ISSUE THREAD

**Issue by meck93** [nikzaugg/Go-Game#3]
When a player wants to execute a move which is deemed invalid: 
* the message invalid will be display and
* no token is placed on the board. 

**Bug:** But the current player changes/switches even though the player has not made a move or passed. 
**Fix:** Player should be asked again to execute a move. Current player doesn't change after an invalid move.

**Comment by alexscheitlin** [comment]
I was not able to recreate your situation but found another one:

- start a new game
- place one black and one white stone according to the image below
![image](https://user-images.githubusercontent.com/22471495/32994129-68420c66-cd63-11e7-9fca-8674fbc2bee2.png)

Now it's blacks turn again. Try to place the stone in the upper right corner, the move is valid but no stone gets added to the board. The function `place_stone` returns true even though the variable `is_valid` is `False` and no stone was added to the board. Thus, the move is considered as finished, the message `Nice Move!` is displayed, and it's the next players turn.
